### ISSUE TITLE
Énumération

### ISSUE THREAD

**Issue by Alfa16bravo** [hydrausb3/HydraDancer#107]
hello, that I connect any device I block on Querying results and nothing else happens here is the cmd (windows 11)

HydraDancer host controller
Select your action:
1)  Set verbosity ON
2)  Set verbosity OFF (default)
3)  Auto mode
4)  Enumerate Audio
5)  Enumerate CDC
6)  Enumerate HID
7)  Enumerate Image
8)  Enumerate Printer
9)  Enumerate Mass Storage
10) Enumerate Smart Card
11) Enumerate Personal Healthcare
12) Enumerate Video
13) Enumerate DFU
14) Enumerate FTDI
15) Enumerate Hub
98) Print logs
99) Disconnect Current Device

0) Exit
> 1
Verbosity turned ON
HydraDancer host controller
Select your action:
1)  Set verbosity ON
2)  Set verbosity OFF (default)
3)  Auto mode
4)  Enumerate Audio
5)  Enumerate CDC
6)  Enumerate HID
7)  Enumerate Image
8)  Enumerate Printer
9)  Enumerate Mass Storage
10) Enumerate Smart Card
11) Enumerate Personal Healthcare
12) Enumerate Video
13) Enumerate DFU
14) Enumerate FTDI
15) Enumerate Hub
98) Print logs
99) Disconnect Current Device

0) Exit
> 3
Enumeration has started
It can take up to 5 seconds (timeout) if the device is not supported by the ToE

                  Device Descriptor        Configuration Descriptor
Status           Class SubClass Protocol    Class SubClass Protocol
Resetting board
Resetting descriptors
Resetting descriptors
Setting device descriptor
Setting configuration descriptor
Setting configuration descriptor
Connecting the device
Querying results...

**Comment by bvernoux** [comment]
Could you clarify what was your issue and how do you have solved it ? (maybe not using 2 USB cables other ?)

**Comment by Alfa16bravo** [comment]
hello, the connections between the serdes ports were a priori of poor quality, I replaced with a female connector below the top card, and the problem is solved.
